### ISSUE TITLE
How to implement PushKit

### ISSUE THREAD

**Issue by saroar** [kurzdigital/Whale#1]
how to implement PushKit with App? when my app is close pushKit will help to run background for incoming call

**Comment by ChristianNorbertBraun** [comment]
As this is not part of the demo project, I can only provide you with the official apple documentation:
https://developer.apple.com/documentation/pushkit

**Comment by saroar** [comment]
thanks but i try your code does not work that's why can i request you to app push request into your app if you will have free time thanks already 3 days does get success 
Thanks again

**Comment by fukemy** [comment]
@saroar hi bro, im stucking like you with pushkit, can you provide something? Thanks so much

**Comment by saroar** [comment]
@fukemy do you have bitbucket ?

**Comment by fukemy** [comment]
yes i have bro dungdv01852@gmail.com

**Comment by fukemy** [comment]
i hate ios 14 when the incoming call screen is minimized, that bad and hard to control with multi incoming call TT^TT
